import '@styles/globals.scss'
import { Inter } from 'next/font/google'

import Nav from '@components/navbar/index.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Nav />
        <div style={{ paddingTop: '15vh' }}>{children}</div>
      </body>
    </html>
  )
}
